version: "3.8"

services:
  db:
    image: postgres:13.0
    environment:
      - POSTGRES_DB=synergy
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  react:
    build: ./reactapp
    command: npm start
    volumes:
      - '.:/reactapp'
      - '/reactapp/node_modules'
    ports:
      - 3001:3000

